### ISSUE TITLE
[Feature] Implement Song - POST Route 

### ISSUE THREAD

**Issue by yarelismartin** [yarelismartin/Tuna-Piano#1]
### **Description**  
Implement the [POST ] route for the [Song] entity. This route should allow for the [CREATE action] of [Song] data in the database.

- **Entity**: Song
- **Action**: POST 

---

### **Task Breakdown**

- [x] Include endpoint in  the `{{Song}}API.cs` file within the `APIs` folder.
- [x] Define the route path as `/api/songs`.
- [ ] Handle request validation and data persistence.
- [ ]  Implement error handling and appropriate status codes.
- [ ]  Test on Swagger 

---

### **Request**

- **HTTP Method**: POST
- **Path**: `/api/songs`
- **Body**: 
```
{
  "title": "My Song",
  "artist_id": 123,
  "album": "My Album",
  "length": 180
}
 ```

### **Response**
- **Body**: 
- **Status Code**: 
```
{
  "id": 456,
  "title": "My Song",
  "artist_id": 123,
  "album": "My Album",
  "length": 180
}
 ```
