### ISSUE TITLE
[song] - [DELETE] Route 

### ISSUE THREAD

**Issue by yarelismartin** [yarelismartin/Tuna-Piano#2]
### **Description**  
Implement the [delete] route for the [song] entity. 

- **Entity**: SONG
- **Action**: DELETE

---

### **Task Breakdown**

- [ ] Include endpoint in  the `{{Song}}API.cs` file within the `APIs` folder.
- [ ] Define the route path as `/api /songs/{songId}`.
- [ ] Handle request validation and data persistence.
- [ ]  Implement error handling and appropriate status codes.
- [ ]  Test on Swagger 

---

### **Request**

- **HTTP Method**: 
- **Path**: `/api /songs/{songId}`
- **Body**:
```

 ```

### **Response**
- **Body**: 
- **Status Code**: 204 No Content
```

 ```
