### ISSUE TITLE
[Song] - [Update ] Route 

### ISSUE THREAD

**Issue by yarelismartin** [yarelismartin/Tuna-Piano#3]
### **Description**  
Implement the [Update ] route for the [Song] entity. 

- **Entity**: Song
- **Action**: Update 

---

### **Task Breakdown**

- [ ] Include endpoint in  the `{{Song}}API.cs` file within the `APIs` folder.
- [ ] Define the route path as `/api/songs/{songId}`.
- [ ] Handle request validation and data persistence.
- [ ]  Implement error handling and appropriate status codes.
- [ ]  Test on Swagger 

---

### **Request**

- **HTTP Method**: PUT
- **Path**: `/api/songs/{songId}`
- **Body**:
```
{
  "title": "Updated Song Title",
  "artist_id": 123,
  "album": "Updated Album Name",
  "length": 240
}
 ```

### **Response**
- **Status Code**: 200 OK
- **Body**: 
```
{
  "id": {songId},
  "title": "Updated Song Title",
  "artist_id": 123,
  "album": "Updated Album Name",
  "length": 240
}
 ```
